[package]
name = "photo-archiver"
version = "0.1.0"
authors = ["Sean Purcell <me@seanp.xyz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
google-photoslibrary1 = "2.0.4"
yup-oauth2 = "5.1.0"
